### ISSUE TITLE
Build error: 'SHRT_MAX' is defined in header '<climits>'; did you forget to '#include <climits>'?

### ISSUE THREAD

**Issue by fractalf** [igorski/VSTSID#11]
```
/src/synth.cpp:28:1: note: 'SHRT_MAX' is defined in header '<climits>'; did you forget to '#include <climits>'?
```
I got this error when building for linux.
I added `#include <climits>` as suggested and it worked.

FYI

**Update**:
When running it in Bitwig it crashes with this:
```
Contents/x86_64-linux/vstsid.so: undefined symbol: pango_layout_set_text
```
...that's pretty much how deep I can go ;)

**Comment by igorski** [comment]
Thanks for pointing out the missing import.
The Bitwig issue will be addressed as part of https://github.com/igorski/VSTSID/pull/13

**Comment by dromer** [comment]
The missing import is not addressed, though ..

**Comment by igorski** [comment]
Indeed it wasn't. It has been actually addressed [here](https://github.com/igorski/VSTSID/pull/18) by a kind contribution. Excuse the delay.
