### ISSUE TITLE
Does not work in latest Reaper 6.78

### ISSUE THREAD

**Issue by 9Skrip** [igorski/VSTSID#12]
Nor VST2  nor VST3
no Sound at all
only Spikes when moving the ringmodulator slider

**Comment by igorski** [comment]
Thanks for reporting. This will be tackled as part of https://github.com/igorski/VSTSID/pull/13

**Comment by kiwijam** [comment]
Seems to work in the other hosts I've tried, but complete silence in Reaper x64 on Windows (with VST2 and VST3) here too.

**Comment by igorski** [comment]
This has been addressed in [version 1.1.2](https://github.com/igorski/VSTSID/commit/382a790a55fc437e3b60f710065dd1532b2d153e), which is now also available for download on the website.
